export const AUTH_LOGIN_CHECK = 'LOGIN_CHECK';
export const AUTH_LOGIN_INPUT_HANDELING = 'AUTH_LOGIN_INPUT_HANDELING';
export const AUTH_GET_LOGIN_DATA = 'AUTH_GET_LOGIN_DATA';
export const AUTH_POST_LOGOUT = 'AUTH_POST_LOGOUT';
export const AUTH_TOKEN_SERVICE = 'TOKEN_SERVICE';
export const AUTH_EMAIL_CHECK = 'AUTH_EMAIL_CHECK';
export const AUTH_PASSWORD_UPDATE = 'AUTH_PASSWORD_UPDATE';
export const EMPTY_SIGNUP_MESSAGE = 'EMPTY_SIGNUP_MESSAGE';

// Auth Reducer
export const GET_AUTH_DATA = 'GET_AUTH_DATA';
export const GET_LOGOUT = 'GET_LOGOUT';
export const EMPTY_LOGIN_MESSAGE = 'EMPTY_LOGIN_MESSAGE';

// Theme Reducer Change Theme
export const GET_THEME = 'GET_THEME';
export const SET_THEME = 'SET_THEME';