export const SCANNER_INPUT_CHANGE = 'SCANNER_INPUT_CHANGE';
export const SCANNED_ITEM = 'SCANNED_ITEM';
export const SCANNED_ITEM_NOT_FOUND = 'SCANNED_ITEM_NOT_FOUND';
export const SCANNED_ITEM_NOT_FOUND_NETWORK_ERROR =
  'SCANNED_ITEM_NOT_FOUND_NETWORK_ERROR';
export const CLEAR_SCANNED_ITEM_STATUS = 'CLEAR_SCANNED_ITEM_STATUS';
