export const POST_INIT = 'POST_INIT';
export const SEARCH_POST = 'SEARCH_POST';
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REFRESH_POSTS_LIST = 'REFRESH_POSTS_LIST';
export const RESET_FORM = 'RESET_FORM';
export const DELETE_POST = 'DELETE_POST';

export const POST_DELETE_INIT = "POST_DELETE_INIT";
export const POST_DELETE_SUCCESSFUL = "POST_DELETE_SUCCESSFUL";
export const POST_DELETE_FAILED = "POST_DELETE_FAILED";
